### PR TITLE
Fix doubled ".gpx" file extension (FS#1070).

### PR DESCRIPTION
**Pull request by SamsonovAnton**

### CODE REVIEW

**Comment by bdbcat** [comment]
Anton...

Please rebase to opencpn master, and I will merge.

**Comment by SamsonovAnton** [comment]
Sorry, I do not quite get it. Currently there are no new publicly visible commits in master branch of SaltyPaws/route_pi@f7c230b628cc63cf53c4cfbbd37e15f164f53258 for almost 2 years; neither does OpenCPN/OpenCPN@59fd1f7e446514583950f195e0731243ce476e10 have *plugins/route_pi* directory in master branch. Otherwise, my *OpenCPN* copy should be on par with upstream, but I have no idea how this could affect *route_pi*.

Perhaps I am missing something obvious due to little experience with collaborative development in general and GitHub in particular. Would you be so kind to explain? I know what rebasing is, — I just do not understand *what* should I rebase against.

**Comment by rgleason** [comment]
Anton, I don't think Walter has been maintaining this because Pavel had a pull request sometime ago, to update to standalone build etc. and Walter never merged it. Pavel had cloned route_pi, which was what I used to build because it was more current, now I can't find that one either. He must have deleted it. Perhaps someone capable should take this over, as was done to update LogbookKonni?  PS: Walter did say he was going to update Calculator and Calculator_muparser to work with windows a little while ago, so he does respond sometimes.

**Comment by rgleason** [comment]
PS: It would be wonderful to get this current with your improvements too.

**Comment by SamsonovAnton** [comment]
Thank you, Rick, that explains a lot. It looks like I must re-target all my patches against the fork by Pavel. Will need some time to think how to accomplish it in a more graceful way than just to drop my own repo and recreate the branches manually.

**Comment by rgleason** [comment]
Anton, git is still a learning experience for me. Right now, because of bdbcat's response (which I don't understand entirely), I am wondering if bdbcat was considering incorporating those changes in the great route features of Opencpn please [rebase to "opencpn master"]  as well as Pavel's repos of route_pi, in any case I would wait for bdbcat to respond.  Maybe they intend to simply wrap Walter's great circle route into Opencpn entirely?

**Comment by bdbcat** [comment]
Rick...

My reply was hasty, and not thought out.  I misread "route_pi".

I now cannot figure out why I am getting notifications for SaltyPaws
github activity.  But no matter...

Anyway, carry on as suggested earlier.  I have no immediate plans to
bring route_pi into master or the OCPN core.

Sorry for the confusion.
Dave

**Comment by rgleason** [comment]
Thank you Dave,
Anton, why don't you take on updating  SaltyDog's plugin simply by using your repository (clone Pavel's repository first) ?  -Walter does not seem to have the time or the interest at the moment.
Then Pavel will merge your pull requests when he needs to build plugins for release.
Also I can clone your repos and build for windows.
Is it possible to make pull requests to Pavel's repos and SaltyDog's?
Anyway, just a thought.

**Comment by SamsonovAnton** [comment]
> Why don't you take on updating SaltyDog's plugin simply by using your repository (clone Pavel's repository first)?

It was a bit more difficult than it may seem, but I found a way that worked:

1. Delete your forked repository on GitHub.
2. Fork again from the right source.
3. Adjust upstream URL in local repo.
4. Fetch all remotes and merge *master*.
5. Create a new branch based on *master* and merge in the original *fix_...* branch.
6. Rebase that branch to remove the dummy "merge" commit.
7. Push to your remote and create pull request.
8. …
9. PROFIT!

Here is the result: nohal/route_pi#1 — let us see how it will proceed.

**Comment by SamsonovAnton** [comment]
As an alternative, GitHub allows to transfer repository ownership to another user, that could be the solution, provided that there is no way to re-root forked repos. But, as there are too few pull requests in *SaltyPaws/route_pi*, it will be easier for everyone to just delete and fork again.

**Comment by rgleason** [comment]
I can build yours changes by cloning, and so can pavel. Sorry about the git work. I think I followed most of it except 6  Thank you.

**Comment by SaltyPaws** [comment]
Hi,

Please let me know who would like to work on the plugins and the github
accounts. This way I can give you permissions on github to make the
necessitated changes to the repository. I will be available to work on the
plugins starting Monday 2nd. However, I would need some help with how the
new build system works. In addition, I am programming and testing the
plugins using Ubuntu Linux. I would also really appreciate some help with
the windows compiling and beta testing part. Would this kind of cooperation
work?

Walbert - SaltyPaws

**Comment by rgleason** [comment]
Dear Wally 
I am happy to build for windows and test. Perhaps Pavel, Anton and I could use the permission. I would use it sparingly. .
I think Pavel because he makes improvements before issuing new versions, and Anton because he has been fixing it.

**Comment by rgleason** [comment]
PS Looking forward to working with you.

**Comment by SamsonovAnton** [comment]
> Perhaps Pavel, Anton and I could use the permission.

No, I do *not* volunteer to push directly to the repository: not only because my VCS skills are low, but mainly because I strongly believe that the less people have write access — the better, and peer review is always a good idea regardless of competence level.

**Comment by SaltyPaws** [comment]
.gpx fix has been implemented.

**Pull request merged**
